name: Continuous Integration

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: latest
      - name: Build project
        run: lein uberjar

